name: Bug Report
description: Report if a bug has occurred.
body:
  - type: textarea
    attributes: 
      label: The problem
      description: Provide details of the bug, how to get the bug, etc.
      value: |
        ### Description 
        <!-- Describe the bug -->

        ### To produce the bug 
        <!-- A clear step by step instructions on how to reproduce the bug -->

        ### OS and Browser Version
        <!-- Please provide your device's and browser's information -->
        Device: 
        OS Version: 

        Browser: 
        App Version: 
    validations:
      required: true
  - type: textarea 
    attributes:
      label: Screenshot/Screen recording
      description: Add a screenshot or a screen recording of the bug
      placeholder: You can drag and drop the file here.
  - type: textarea 
    attributes:
      label: Traceback
      description: Paste the traceback here if you got a crash (the one with Mizu5 'I'm sorry' sticker.)
      placeholder: You can drag or drop the file here.
    validations:
      required: false
